name: Feature request
description: 게임에 추가될 새로운 기능을 제안해주세요.
labels: [enhancement]
type: Feature
title: '[Feat]: '
body:
  - type: textarea
    id: description
    attributes:
      label: 기능 설명
      description: 이 기능이 무엇인지 간략하게 설명해주세요. 이 기능이 프로젝트에 어떤 가치를 더할 수 있을지 설명해주세요.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 기대할 효과
      description: 예) 플레이어가 움직일 수 있다. 코드 패턴이 더 단조로워진다.
    validations:
      required: true

  - type: textarea
    id: etc
    attributes:
      label: 추가 정보
      description: 기능에 대한 다른 정보를 작성해주세요.
      placeholder: 아이디어 스케치, 기획 자료
    validations:
      required: false
