name: PR labeler
on:
  issues :
    types: [opened, edited, milestoned]
  pull_request_target :
    types: [opened]

jobs:
  labeler:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
    steps:
      - name : Check Labels
        uses : jimschubert/labeler-action@v2
        with :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}