name: Release Drafter
on:
  push:
    branches:
      - main

  #pull_request:
    #types: [opened, reopened, synchronize]
  #pull_request_target:
    #types: [opened, reopened, synchronize]

permissions:  # 🔥 GITHUB_TOKEN 권한 추가
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}